// DO NOT EDIT THIS FILE
// IT WILL BE OVERWRITTEN BEFROE DEPLOYMENT

let m0 = 0.5;
let m1 = 0.5;
let m2 = 0.5;
let m3 = 0.5;
let m4 = 0.5;

const queryString = window.location.search;
console.log(queryString)
if(queryString){
  getParams(queryString);
}

function truncate(i) {
    return Math.max(Math.min(i, 1), 0);
}
function getParam(urlParams, p) {
    const param = urlParams.get(p);
    if (param) {
        return truncate(parseFloat(param));
    }
    return null;
}
function getParams(queryString) {
    const urlParams = new URLSearchParams(queryString);
    m0 = getParam(urlParams, "m0");
    m1 = getParam(urlParams, "m1");
    m2 = getParam(urlParams, "m2");
    m3 = getParam(urlParams, "m3");
    m4 = getParam(urlParams, "m4");
}
window.addEventListener("message", (e) => {
    var data = e.data;

    if ("editartQueryString" in data) {
        getParams(data["editartQueryString"]);
        draw();
    }
});